# Generated by Django 4.1.4 on 2023-05-18 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0024_user_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL)),
                ('tier', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.subtier')),
            ],
        ),
    ]
