# Generated by Django 4.1.4 on 2023-05-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tier',
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
