# Generated by Django 4.1.4 on 2023-01-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fullname',
        ),
        migrations.AddField(
            model_name='user',
            name='accounts',
            field=models.ManyToManyField(default=None, null=True, to='users.account'),
        ),
    ]
