# Generated by Django 4.1.4 on 2023-01-23 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='uuid',
            field=models.CharField(default='a567221b-3500-417f-bba3-7587b286e455', max_length=36),
        ),
        migrations.AddField(
            model_name='subtier',
            name='uuid',
            field=models.CharField(default='ea4b23be-85b7-4396-b58c-c84639f14a1a', max_length=36),
        ),
    ]
