# Generated by Django 4.1.4 on 2023-01-23 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_account_uuid_subtier_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='uuid',
            field=models.CharField(default='f6e5fa0a-29eb-4546-b894-6a1283ab4728', max_length=36),
        ),
        migrations.AlterField(
            model_name='subtier',
            name='uuid',
            field=models.CharField(default='cd77b7b6-401e-4a84-a418-ac00869749a3', max_length=36),
        ),
    ]
