# Generated by Django 4.1.4 on 2023-01-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_account_uuid_alter_subtier_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='uuid',
            field=models.CharField(default='<function uuid4 at 0x7fe9cd2291c0>', max_length=36),
        ),
        migrations.AlterField(
            model_name='subtier',
            name='uuid',
            field=models.CharField(default='<function uuid4 at 0x7fe9cd2291c0>', max_length=36),
        ),
    ]
