# Generated by Django 4.1.4 on 2023-01-23 02:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_account_uuid_alter_subtier_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='subtier',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
