# Generated by Django 4.1.4 on 2023-01-23 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_account_uuid_alter_subtier_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_date', models.DateField(auto_now=True)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='sub_info',
            field=models.ManyToManyField(to='users.subinfo'),
        ),
    ]
