# Generated by Django 4.1.4 on 2023-01-23 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_subinfo_user_sub_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='subinfo',
            name='tier',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.subtier'),
        ),
    ]
