# Generated by Django 4.1.4 on 2023-01-25 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_subinfo_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.IntegerField(verbose_name=[(0, 'Subscription'), (1, 'One time payment')])),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=5)),
                ('from_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='history',
            field=models.ManyToManyField(to='users.transaction'),
        ),
    ]
