# Generated by Django 4.1.4 on 2023-01-25 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_transaction_account_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='subinfo',
            name='subscriber',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to=settings.AUTH_USER_MODEL),
        ),
    ]
