# Generated by Django 4.1.4 on 2023-01-26 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_subinfo_subscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subinfo',
            old_name='sub_date',
            new_name='date',
        ),
    ]
