# Generated by Django 4.1.4 on 2023-01-27 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_sub_date_subinfo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activity',
            field=models.CharField(default='Good person', max_length=32),
        ),
    ]
