# Generated by Django 4.1.4 on 2023-01-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_user_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtier',
            name='description',
            field=models.TextField(default=None, max_length=1000, null=True),
        ),
    ]
