# Generated by Django 4.1.4 on 2023-02-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activity',
            field=models.CharField(default='Good person', max_length=300),
        ),
    ]
