# Generated by Django 4.1.4 on 2023-02-02 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_user_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Color'), (1, 'Gradient'), (2, 'Image')])),
                ('data', models.CharField(max_length=255)),
                ('mask', models.IntegerField(default=4095, null=True)),
                ('mask_opacity', models.FloatField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background', to='users.customizationdata')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner', to='users.customizationdata')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='customizing',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customizationsettings'),
        ),
    ]
