# Generated by Django 4.1.4 on 2023-02-02 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_customizationdata_mask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizationsettings',
            name='background',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='background', to='users.customizationdata'),
        ),
        migrations.AlterField(
            model_name='customizationsettings',
            name='banner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner', to='users.customizationdata'),
        ),
    ]
