# Generated by Django 4.1.4 on 2023-02-02 18:47

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_customizationsettings_background_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizationdata',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=users.models.upload_to),
        ),
        migrations.AlterField(
            model_name='customizationdata',
            name='data',
            field=models.CharField(default=True, max_length=255, null=True),
        ),
    ]
