# Generated by Django 4.1.4 on 2023-03-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_customizationsettings_background_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(default=None, null=True),
        ),
    ]
